use_frameworks!

platform :ios, '12.0'

target 'GeovisEarthKit_Example' do
  pod 'GeovisEarthKit', :path => '../'
  
  pod 'MapboxMaps', '11.7.1'

  target 'GeovisEarthKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
       end
    end
  end
end

